name:                dynamic-array
version:             0.1.0.0
license:             BSD3
author:              "Andr치s Kov치cs"
maintainer:          "puttamalac@gmail.com"
copyright:           "2018-2020 Andr치s Kov치cs"

dependencies:
- base >= 4.7 && < 5

default-extensions:
  - GeneralizedNewtypeDeriving
  - KindSignatures
  - LambdaCase
  - MagicHash
  - RankNTypes
  - RoleAnnotations
  - UndecidableInstances

ghc-options:
  - -Wall
  - -Wno-missing-signatures
  - -Wno-name-shadowing
  - -Wno-unused-do-bind
  - -Wno-unused-matches
  - -Wno-partial-type-signatures
  - -O2
  - -fllvm

library:
  source-dirs: .
  dependencies:
    - primdata
  # ghc-options:
  #   - -ddump-simpl
  #   - -dsuppress-all
  #   - -dno-suppress-type-signatures
  #   - -ddump-to-file
