
name:        setoidtt
version:     0.1.0.0
license:     BSD2
category:    Language
description: "Implementation of a variant of setoid type theory"

default-extensions:
- BangPatterns
- BlockArguments
- CPP
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveAnyClass
- DerivingStrategies
- DerivingVia
- EmptyCase
- ExplicitNamespaces
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- InstanceSigs
- LambdaCase
- MagicHash
- MultiParamTypeClasses
- NoMonomorphismRestriction
- OverloadedStrings
- PartialTypeSignatures
- PatternSynonyms
- PolyKinds
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- Strict
- TemplateHaskell
- TupleSections
- TypeApplications
- TypeFamilies
- TypeOperators
- UnboxedTuples
- UnicodeSyntax
- ViewPatterns

ghc-options:
- -Wall
- -Wno-name-shadowing
- -Wno-missing-signatures
- -Wno-unused-do-bind
- -Wno-unused-matches
- -Wno-partial-type-signatures
- -Wno-type-defaults
- -Wno-missing-pattern-synonym-signatures
- -O2
# - -fllvm
- -fplugin-opt=Test.Inspection.Plugin:skip-O0
- -ddump-simpl
- -dsuppress-all
- -dno-suppress-type-signatures
- -ddump-to-file
- -ddump-stg
- -ddump-cmm

dependencies:
  - base

data-files:
  - bench/parse01.stt

library:
  source-dirs:
    - src
  dependencies:
  - bytestring
  - containers
  - directory
  - dynamic-array
  - flatparse
  - ghc-prim
  - hashable
  - inspection-testing
  - primdata
  - template-haskell
  - time
  - unordered-containers

executables:
  setoidtt:
    source-dirs:
      - main
    main: Main.hs
    dependencies:
      - setoidtt
    ghc-options:
      - -rtsopts

  setoidtt-bench:
    source-dirs:
      - bench
    main: Bench.hs
    dependencies:
      - gauge
      - flatparse
      - setoidtt
    ghc-options:
      - -rtsopts
