
name:        setoidtt
version:     0.1.0.0
license:     BSD2
category:    Language
description: "Implementation of a variant of setoid type theory"

default-extensions:
- BangPatterns
- BlockArguments
- CPP
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveAnyClass
- DerivingStrategies
- DerivingVia
- EmptyCase
- ExplicitNamespaces
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- InstanceSigs
- LambdaCase
- MagicHash
- MultiParamTypeClasses
- NoMonomorphismRestriction
- OverloadedStrings
- PartialTypeSignatures
- PatternSynonyms
- PolyKinds
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- Strict
- TemplateHaskell
- TupleSections
- TypeApplications
- TypeFamilies
- TypeOperators
- UnboxedTuples
- UnicodeSyntax
- ViewPatterns

ghc-options:
- -Wall
- -Wno-name-shadowing
- -Wno-missing-signatures
- -Wno-unused-do-bind
- -Wno-unused-matches
- -Wno-partial-type-signatures
- -Wno-type-defaults
- -Wno-missing-pattern-synonym-signatures

dependencies:
- base >= 4.7 && < 5
- bytestring
- containers
- dynamic-array
- ghc-prim
- primdata
- text-short
- time
- unordered-containers
- gauge
- megaparsec
- text

source-dirs:
  - src

library:
  ghc-options:
    - -O2
    - -fllvm
    - -ddump-simpl
    - -dsuppress-all
    - -dno-suppress-type-signatures
    - -ddump-to-file

executable:
  main: Main.hs
  ghc-options:
    - -O2
    - -fllvm
    - -rtsopts
