
name:        setoidtt
version:     0.1.0.0
license:     BSD2
category:    Language
description: "Implementation of a variant of setoid type theory"

default-extensions:
- BangPatterns
- BlockArguments
- CPP
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveAnyClass
- DerivingStrategies
- DerivingVia
- EmptyCase
- ExplicitNamespaces
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- InstanceSigs
- LambdaCase
- MagicHash
- MultiParamTypeClasses
- NoMonomorphismRestriction
- OverloadedStrings
- PartialTypeSignatures
- PatternSynonyms
- PolyKinds
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- Strict
- TemplateHaskell
- TupleSections
- TypeApplications
- TypeFamilies
- TypeOperators
- UnboxedTuples
- UnicodeSyntax
- ViewPatterns

ghc-options:
- -Wall
- -Wno-name-shadowing
- -Wno-missing-signatures
- -Wno-unused-do-bind
- -Wno-unused-matches
- -Wno-partial-type-signatures
- -Wno-type-defaults
- -Wno-missing-pattern-synonym-signatures
- -ddump-simpl
- -dsuppress-all
- -dno-suppress-type-signatures
- -ddump-to-file

dependencies:
- base
- bytestring
- containers
- dynamic-array
- flatparse
- ghc-prim
- primdata
- template-haskell
- time
- unordered-containers
- directory

data-files:
  - bench/parse01.stt

executables:
  setoidtt:
    source-dirs:
      - src
    main: Main.hs
    ghc-options:
      - -O2
      # - -fllvm
      - -rtsopts

  setoidtt-bench:
    source-dirs:
      - src
      - bench
    main: Bench.hs
    dependencies:
      - gauge
      - flatparse
    ghc-options:
      - -O2
      # - -fllvm
      - -rtsopts
