
name:        setoidtt
version:     0.1.0.0
license:     BSD2
category:    Language
description: "Implementation of a variant of setoid type theory"

default-extensions:
- BangPatterns
- BlockArguments
- CPP
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveAnyClass
- DerivingStrategies
- DerivingVia
- EmptyCase
- ExplicitNamespaces
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- InstanceSigs
- LambdaCase
- MagicHash
- MultiParamTypeClasses
- NoMonomorphismRestriction
- OverloadedStrings
- PartialTypeSignatures
- PatternSynonyms
- PolyKinds
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- Strict
- TemplateHaskell
- TupleSections
- TypeApplications
- TypeFamilies
- TypeOperators
- UnboxedTuples
- UnicodeSyntax
- ViewPatterns

ghc-options:
- -Wall
- -Wno-name-shadowing
- -Wno-missing-signatures
- -Wno-unused-do-bind
- -Wno-unused-matches
- -Wno-partial-type-signatures
- -Wno-type-defaults
- -Wno-missing-pattern-synonym-signatures
- -O2
- -fplugin-opt=Test.Inspection.Plugin:skip-O0
# - -ddump-simpl
# - -dsuppress-all
# - -dno-suppress-type-signatures
# - -ddump-to-file
# - -ddump-stg
# - -ddump-cmm


dependencies:
- base
- bytestring
- containers
- directory
- dynamic-array
- flatparse
- ghc-prim
- hashable
- inspection-testing
- primdata
- template-haskell
- time
- unordered-containers

data-files:
  - bench/parse01.stt

executables:
  setoidtt:
    source-dirs:
      - src
    main: Main.hs
    ghc-options:
      - -rtsopts


  # setoidtt-bench:
  #   source-dirs:
  #     - src
  #     - bench
  #   main: Bench.hs
  #   dependencies:
  #     - gauge
  #     - flatparse
  #   ghc-options:
  #     - -O2
  #     # - -fllvm
  #     - -rtsopts
