[package]
name = "rustbench"
version = "0.1.0"
authors = ["kutta <puttamalac@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "5"
bencher = "0.1.5"

[[bench]]
name = "bench"
harness = false
